### ISSUE TITLE
notEmpty() deprecated in cake 3.0.2

### ISSUE THREAD

**Issue by cgowman** [Schlaefer/cakephp-simple-captcha#1]
I have taken a look at \Siezi\SimpleCaptcha\Model\Validation\SimpleCaptchaValidator() and noticed on line 47 is using notEmpty() rule, and so preceded to replace it with notBlank() rule. However I am still being throw the same Deprecated message (below).

Deprecated (16384): Validation::notEmpty() is deprecated. Use Validation::notBlank() instead. [CORE/src/Validation/Validation.php, line 58]

Cake\Validation\Validation::notEmpty() - CORE/src/Validation/Validation.php, line 58
ReflectionMethod::invokeArgs() - [internal], line ??
Cake\Validation\RulesProvider::__call() - CORE/src/Validation/RulesProvider.php, line 70
Cake\Validation\RulesProvider::notEmpty() - CORE/src/Validation/ValidationRule.php, line 140
Cake\Validation\ValidationRule::process() - CORE/src/Validation/ValidationRule.php, line 140
Cake\Validation\Validator::_processRules() - CORE/src/Validation/Validator.php, line 567
Cake\Validation\Validator::errors() - CORE/src/Validation/Validator.php, line 131
App\Controller\ContactsController::index() - APP/Controller/ContactsController.php, line 37
Cake\Controller\Controller::invokeAction() - CORE/src/Controller/Controller.php, line 410
Cake\Routing\Dispatcher::_invoke() - CORE/src/Routing/Dispatcher.php, line 114
Cake\Routing\Dispatcher::dispatch() - CORE/src/Routing/Dispatcher.php, line 87
[main] - ROOT/webroot/index.php, line 37

**Comment by Schlaefer** [comment]
Thanks for the report. Using 'notBlank' also removes the deprecated message for me (cake 3.0.5).
