### ISSUE TITLE
Add random operator

### ISSUE THREAD

**Issue by vnt** [Schlaefer/cakephp-simple-captcha#3]
Hi,
for the next version, can you add the random operators ( -, +, *, : )?
Best regards,
D.

**Comment by Schlaefer** [comment]
The plugin also utilizes that the arguments if put in different order have a different result. With that + and * are not desirable. Divisions require more mental work and special care to avoid fractions. With that I would stick to just -. To my knowledge no bot got past this plugin so far, and there's no value in operator diversity.
